### ISSUE TITLE
1. Dane na histogramie zmian par  walutowych.

### ISSUE THREAD

**Issue by DorianWlodarczyk** [IIS-ZPI/ZPI2022_zaoczni_Semafor#61]
Priorytet : Duży
Powtarzalność: Za każdym razem kiedy jest tworzony histogram zmian walutowych.
Przeglądarka: Google Chrome
Lokalizacja: Aplikacja > Rozkład zmian par walutowych
Kroki do powtórzenia:
1.Uruchomić aplikacje.
2.Wchodzimy na adres aplikacji: [](http://localhost:3000/ZPI2022_zaoczni_Semafor)
3.Wybrać "Rozkład zmian par walutowych".
4.Wybrać 2 waluty np. [EUR/GBP.]
5.Kliknąć "szukaj" znajdujące się po prawej stronie od walut.

Rezultat testu: Dane na wykresie nie posiadają żadnej jednostki. Powinny być przedstawiane w procentach z maksymalnie 2 miejscami po przecinku.

**Comment by Oxozon4** [comment]
Błąd został rozwiązany i możliwe jest ponowne przetestowanie

**Comment by DorianWlodarczyk** [comment]
Dane są poprawnie prezentowane.
