### ISSUE TITLE
2. Osie histogramu

### ISSUE THREAD

**Issue by DorianWlodarczyk** [IIS-ZPI/ZPI2022_zaoczni_Semafor#62]
Priorytet : Duży
Powtarzalność: Za każdym razem kiedy jest tworzony histogram zmian par walutowych.
Przeglądarka: Google Chrome
Lokalizacja: Aplikacja > Rozkład zmian par walutowych
Kroki do powtórzenia:
1.Uruchomić aplikacje.
2.Wchodzimy na adres aplikacji: [](http://localhost:3000/ZPI2022_zaoczni_Semafor)
3.Wybrać "Rozkład zmian par walutowych".
4.Wybrać 2 waluty np. [EUR/GBP.]
5.Kliknąć "szukaj" znajdujące się po prawej stronie od walut.
Rezultat testu: Osie histogramu nie posiadają jednostek, dodatkowo każdy pionowy słupek wykresu powinien posiadać zakres własny przedział na osi poziomej.

**Comment by Oxozon4** [comment]
Stworzenie zakresu na osi poziomej okazało się zbyt trudne do zrealizowania przy obecnej bibliotece z której korzystamy do wykresów. Natomiast jednostki zostały dodane

**Comment by Oxozon4** [comment]
Poprawka została dorzucona i możliwe jest ponowne przetestowanie

**Comment by DorianWlodarczyk** [comment]
Osie posiadają jednostki i działają poprawnie a w momencie najechania na dany słupek jest przedział co jest akceptowalne.
