### ISSUE TITLE
3. Tytuł histogramu

### ISSUE THREAD

**Issue by DorianWlodarczyk** [IIS-ZPI/ZPI2022_zaoczni_Semafor#63]
Priorytet : Duży
Powtarzalność: Za każdym razem kiedy jest tworzony histogram zmian par walutowych.
Przeglądarka: Google Chrome
Lokalizacja: Aplikacja > Rozkład zmian par walutowych
Kroki do powtórzenia:
1.Uruchomić aplikacje.
2.Wchodzimy na adres aplikacji: [](http://localhost:3000/ZPI2022_zaoczni_Semafor)
3.Wybrać "Rozkład zmian par walutowych".
4.Wybrać 2 waluty np. [EUR/GBP.]
5.Kliknąć "szukaj" znajdujące się po prawej stronie od walut.
Rezultat testu: Po utworzeniu histogramu , histogram powinien być podpisany walutami jakie są do siebie porównywane.

**Comment by Oxozon4** [comment]
Poprawka została dorzucona i możliwe jest ponowne przetestowanie

**Comment by DorianWlodarczyk** [comment]
Tytuł histogramu działa poprawnie.
