### ISSUE TITLE
4. Aktualny kurs waluty

### ISSUE THREAD

**Issue by DorianWlodarczyk** [IIS-ZPI/ZPI2022_zaoczni_Semafor#64]

**Comment by DorianWlodarczyk** [comment]
Priorytet : Mały
Powtarzalność: Za każdym razem kiedy jest wchodzimy na adres aplikacji.
Przeglądarka: Google Chrome
Lokalizacja: Aplikacja > Analiza waluty
Kroki do powtórzenia:
1.Uruchomić aplikacje.
2.Wchodzimy na adres aplikacji: [](http://localhost:3000/ZPI2022_zaoczni_Semafor)
3.Wybrać "Analiza waluty".
4.Wybrać walutę np. [EUR]
5.Kliknąć "szukaj" znajdujące się po prawej stronie od waluty.
Rezultat testu: Wyświetlanie aktualnego kursu waluty nie jest zawarte w wymaganiach systemu.

**Comment by Oxozon4** [comment]
Poprawka została dorzucona i możliwe jest ponowne przetestowanie

**Comment by DorianWlodarczyk** [comment]
Poprawka zaakceptowana.
