### ISSUE TITLE
5. Wybór waluty nieobsługiwanej przez api.

### ISSUE THREAD

**Issue by DorianWlodarczyk** [IIS-ZPI/ZPI2022_zaoczni_Semafor#65]
Priorytet : Duży
Powtarzalność: Za każdym razem kiedy wybieramy niepoprawną walute.
Przeglądarka: Google Chrome
Lokalizacja: Aplikacja > Analiza waluty oraz Rozkład zmian par walutowych
Kroki do powtórzenia:
1.Uruchomić aplikacje.
2.Wchodzimy na adres aplikacji: [](http://localhost:3000/ZPI2022_zaoczni_Semafor)
3.Wybrać "Analiza waluty" bądź "Rozkład zmian par walutowych".
4.Wybrać walutę np. [EUR]
5.Kliknąć "szukaj" znajdujące się po prawej stronie od waluty.
Rezultat testu: Użytkownik powinien mieć do wyboru wyłącznie waluty obsługiwane przez api.

**Comment by DorianWlodarczyk** [comment]
Lista walut i państw które są obsługiwane przez api nbp:
EUR,AUD,NOK,BRL,USD,BGN,CAD,CLP,CNY,HKD,NZD,CZK,DKK,GBP,HUF,ISK,INR,IDR,ILS,JPY,KRW,CHF,MYR,MXN,PHP,RON,SGD,ZAR,SEK,THB,TRY,UAH

**Comment by Oxozon4** [comment]
Poprawka została dorzucona i możliwe jest ponowne przetestowanie

**Comment by DorianWlodarczyk** [comment]
Poprawka spełnia założenia funkcjonalne.
