### ISSUE TITLE
6. Niepoprawne dane walutowe podane przez użytkownika

### ISSUE THREAD

**Issue by DorianWlodarczyk** [IIS-ZPI/ZPI2022_zaoczni_Semafor#66]
Priorytet : Duży
Powtarzalność: Za każdym razem kiedy jedna z walut jest niepoprawna.
Przeglądarka: Google Chrome
Lokalizacja: Aplikacja > Analiza waluty oraz Rozkład zmian par walutowych
Kroki do powtórzenia:
1.Uruchomić aplikacje.
2.Wchodzimy na adres aplikacji: [](http://localhost:3000/ZPI2022_zaoczni_Semafor)
3.Wybrać "Analiza waluty" bądź "Rozkład zmian par walutowych".
4.Wybrać walutę np. [EUR].
5.Kliknąć "szukaj" znajdujące się po prawej stronie od waluty.
Rezultat testu: Użytkownik powinien otrzymać informacje że dane które wpisał są niepoprawne. Zamiast tego aplikacja się zawiesza lub nie reaguje.

**Comment by Oxozon4** [comment]
Po poprawkach w #65 i #67 Problem nie powinien występować

**Comment by Oxozon4** [comment]
Poprawka została dorzucona i możliwe jest ponowne przetestowanie

**Comment by DorianWlodarczyk** [comment]
Użytkownik nie może już wpisywać niepoprawnych danych czyli działa prawidłowo.
