### ISSUE TITLE
7. Wpisanie kraju zamiast waluty

### ISSUE THREAD

**Issue by DorianWlodarczyk** [IIS-ZPI/ZPI2022_zaoczni_Semafor#67]
Priorytet : Mały
Powtarzalność: Za każdym razem kiedy zamiast waluty wpisywane jest państwo operujące na tej walucie.
Przeglądarka: Google Chrome
Lokalizacja: Aplikacja > Analiza waluty oraz Rozkład zmian par walutowych bądź "Rozkład zmian par walutowych".
Kroki do powtórzenia:
1.Uruchomić aplikacje.
2.Wchodzimy na adres aplikacji: [](http://localhost:3000/ZPI2022_zaoczni_Semafor)
3.Wybrać "Analiza waluty" bądź "Rozkład zmian par walutowych".
4.Wybrać państwo.
5.Kliknąć "szukaj" znajdujące się po prawej stronie od waluty.
Rezultat testu: Ten sposób wyszukiwania nie jest zawarty w wymaganiach ale nie wpływa negatywnie na działanie aplikacji.

**Comment by Oxozon4** [comment]
Poprawka została dorzucona i możliwe jest ponowne przetestowanie

**Comment by DorianWlodarczyk** [comment]
Poprawka zaakceptowana,
