### ISSUE TITLE
8.Axes of the currency analysis chart

### ISSUE THREAD

**Issue by DorianWlodarczyk** [IIS-ZPI/ZPI2022_zaoczni_Semafor#79]
Priority : Low
Repeatability : Every time a currency change analysis chart is created.
Browser : Google Chrome
Location : Application > Analiza waluty
Steps to repeat:
1.Launch the application.
2.Go to the application address: [](http://localhost:3000/ZPI2022_zaoczni_Semafor)
3.Select "Currency Analysis."
4.Select the currency e.g. GBP.
5.Select a time range e.g. [1 week].
6.Click "search" located to the right of the currencies.
Test result: The horizontal axis does not need to be signed and the vertical axis should be signed "number of currency change sessions".

**Comment by Oxozon4** [comment]
@DorianWlodarczyk bug should now be fixed and solution can be retested.

**Comment by DorianWlodarczyk** [comment]
The fix was implemented correctly but in some cases the axis signature overlaps the unit.
