### ISSUE TITLE
9. Number of currency change sessions.

### ISSUE THREAD

**Issue by DorianWlodarczyk** [IIS-ZPI/ZPI2022_zaoczni_Semafor#80]
Priority : High
Repeatability : Every time a currency analysis chart is created.
Browser : Google Chrome
Location : Application > Rozkład zmian par walutowych
Steps to repeat:
1.Launch the application.
2.Go to the application address: [](http://localhost:3000/ZPI2022_zaoczni_Semafor)
3.Select "Currency analysis".
4.Select a time interval e.g. 1 week.
5.Select a currency e.g. EUR.
6.Click "search" located to the right of the currencies.
Test result: The chart created is not very realistic. The data should be compared with the previous day.

**Comment by Oxozon4** [comment]
@DorianWlodarczyk bug should now be fixed and solution can be retested.

**Comment by DorianWlodarczyk** [comment]
After a series of tests, the amounts of currency session changes are appropriate.
