### ISSUE TITLE
10. Selection of the starting date in the distribution of changes in currency pairs.

### ISSUE THREAD

**Issue by DorianWlodarczyk** [IIS-ZPI/ZPI2022_zaoczni_Semafor#81]
Priority : Very high
Repeatability : Every time the application is launched.
Browser : Google Chrome
Location : Application > Rozkład zmian par walutowych.
Steps to repeat:
1.Launch the application.
2.Go to the application address: [](http://localhost:3000/ZPI2022_zaoczni_Semafor)

Test result: The system doesn't give you the option to select a time frame only always refers to the last month/quarter.

**Comment by Oxozon4** [comment]
@DorianWlodarczyk bug should now be fixed and solution can be retested.

**Comment by DorianWlodarczyk** [comment]
The selection of the starting day works correctly and handles cases in which the length of the time period would be impossible to choose.
